### ISSUE TITLE
Static libraries

### ISSUE THREAD

**Issue by turbolent** [nh2/static-haskell-nix#28]
Is it possible to use this infrastructure to also build static libraries?

**Comment by nh2** [comment]
I'm not quite clear on what exactly you mean.

Yes, static libs for system libraries are built by static-haskell-nix, so that we can link them into static executables.

Or do you mean static Haskell libs for a particular purpose?

GHC usually already builds `.a` files.

Do you perhaps mean some "bundled" `.a` files that contain all their recursive dependencies?

**Comment by turbolent** [comment]
Right, I was new to cabal and its options. `--enable-static  --disable-shared` builds a static library just fine.
